### ISSUE TITLE
Prices are returned as "double". Prices should never be stored in floats/doubles.

### ISSUE THREAD

**Issue by michael-newsrx** [Xignite/JavaSDK#2]
The SDK returns prices as type "double".

They should be BigDecimal or some other fixed number format that is not subject to "floating point rounding" errors. Or just Strings.

Types of float/double in Java (or any other language) are subject to rounding errors.

Please see for a complete discussion as to why:

http://stackoverflow.com/questions/3730019/why-not-use-double-or-float-to-represent-currency

> Because floats and doubles cannot accurately represent the base 10 multiples we use for money. This issue isn't just for Java, it's for any programming language that uses native floating-point types, as it stems from how computers handle floating-point numbers by default.
> ...
> Representing money as a double or float will probably look good at first as the software rounds off the tiny errors, but as you perform more additions, subtractions, multiplications and divisions on inexact numbers, you'll lose more and more precision as the errors add up. This makes floats and doubles inadequate for dealing with money, where perfect accuracy for multiples of base 10 powers is required.
> 
> A solution that works in just about any language is to use integers instead, and count cents. For instance, 1025 would be $10.25. Several languages also have built-in types to deal with money. Among others, Java has the BigDecimal class, and C# has the decimal type.

**Comment by awalsh128** [comment]
Agreed that prices should be represented by decimal or some fixed point form. Unfortunately, due to legacy reasons on the API themselves, we have left them as this data type. We could coerce them into these values for the SDK but that would misrepresent the API's true types.

**Comment by michael-newsrx** [comment]
Are you saying the API responses having rounding errors in them and that changing how the API response is parsed data type wise won't make it worse?

I was under the impression these are JSON (or SOAP) responses being parsed? Is this not correct?

**Comment by awalsh128** [comment]
The API response values do not have rounding errors. Used as a representation, the data type covers all ranges needed for price values (even sub-sub cents). This may make it prone to computational errors if used as the same type but the API is accurately representing the value. The API's are written against a WSDL that assigns an explicit type on the API's value. The SDK strictly interprets the types as given by the SOAP WSDL (unlike a JSON typed REST interface). Changing that would break functionality for existing customers who depend on SOAP, many who have written programs that are no longer open to modification.

**Comment by michael-newsrx** [comment]
OK, much thanks, that helps understanding a lot.
