### ISSUE TITLE
remove fasterxml (jackson) source files from the project

### ISSUE THREAD

**Issue by chauzer** [Xignite/JavaSDK#3]
it looks like the jackson jars are already defined as dependencies, not sure why the source files from fasterxml (jackson) are also in the com. package? this is causing some issues with my project because my project is picking up the source files for jackson files from this xignite jar

**Comment by michael-newsrx** [comment]
Workaround: https://github.com/michael-newsrx/XigniteSdk

**Comment by cstupi** [comment]
The dependencies have been pulled out of the jar and can now be added separately.
